version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:v2.2.3
    restart: always
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
    ports:
      - 8848:8848
      - 9848:9848
    volumes:
      - ./nacos/logs:/home/nacos/logs

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=skider
    ports:
      - 5432:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
