server:
  port: 3000
#  servlet:
#    context-path: /api

logging:
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss}}){faint} 
    %clr(${LOG_LEVEL_PATTERN:-%5p}) 
    %clr(${PID:- }){magenta} 
    %clr(${LOGGED_APPLICATION_NAME:}[%15.15t]){faint}
    %clr(${LOG_CORRELATION_PATTERN:}){faint}%clr(%40.40logger{39}){cyan} 
    %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}"

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/skider
    username: pg
    password: pg
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        file-extension: yaml
    gateway:
      routes:
        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/articles/**
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/auth/**,/users/**
