server:
  address: localhost
  port: 8082
  servlet:
    context-path: /api

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/skider?currentSchema=sch_article
    username: pg
    password: pg
  jpa:
    #    generate-ddl: true
    hibernate:
      ddl-auto: update

feign:
  client:
    config:
      default:
        connectTimeout: 300 # 连接超时时间
        readTimeout: 1000   # 读超时时间
        loggerLevel: BASIC # 日志级别
  httpclient:
    enable: true
    maxConnections: 200
    maxConnectionsPerRoute: 100

management:
  endpoints:
    web:
      exposure:
        include: "*"
