server:
  address: localhost
  port: 8082
  servlet:
    context-path: /api

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/skider?currentSchema=sch_article
    username: pg
    password: pg
