server:
  address: localhost
  port: 8081
  servlet:
    context-path: /api

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/skider?currentSchema=sch_account
    username: pg
    password: pg
  jpa:
#    generate-ddl: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
